language: node_js

node_js:
  - lts/*

cache:
  directories:
    - node_modules

install:
  - SKIP_SETUP=true npm install

script:
  - npm run lint:styles
  - npm run lint:js
  - npm run build:dist

dist: trusty
sudo: false
