---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: tags
  type: tag_list
  default: []
  label: tags
- name: preview
  type: file
  config:
    maxSize: 10
  label: preview
- name: actions
  type: field_group
  config: {}
  fields:
  - name: source_code_url
    type: text
    config:
      required: false
    label: Source code URL
  - name: preview_url
    type: text
    config:
      required: false
    label: Preview URL
  label: Actions
pages:
- docs/_projects/hackupc-landing.md
