---
label: Project
hide_body: true
display_field: title
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: tags
  type: tag_list
  default: []
  label: tags
- name: preview
  type: file
  config:
    maxSize: 10
  label: preview
- name: source_code_url
  type: text
  config:
    required: false
  label: Source code URL
- name: preview_url
  type: text
  config:
    required: false
  label: Preview URL
pages:
- docs/_projects/gradecalc.json
